deployment

diff --git a/scripts/stop_application b/scripts/stop_application
--- a/scripts/stop_application
+++ b/scripts/stop_application
@@ -7,5 +7,5 @@ cd $CATALINA_HOME
 FILE=./pid.file
 if [ -f "$FILE" ]; then
 	echo "$FILE exists."
-    kill $(cat ./pid.file) || echo "Error Killing process $(cat ./pid.file)"
+    kill $(cat ./pid.file) || echo "Error killing process $(cat ./pid.file)"
 fi
